INSERT INTO Authors (AuthorID, AuthorName)
VALUES
    (1, 'George Orwell'),
    (2, 'J.K. Rowling'),
    (3, 'Agatha Christie'),
    (4, 'Harper Lee'),
    (5, 'Ernest Hemingway'),
    (6, 'Maya Angelou'),
    (7, 'Stephen King'),
    (8, 'Jane Austen'),
    (9, 'F. Scott Fitzgerald'),
    (10, 'Toni Morrison'),
    (11, 'Mark Twain'),
    (12, 'J.R.R. Tolkien'),
    (13, 'Gabriel Garcia Marquez'),
    (14, 'Herman Melville'),
    (15, 'Virginia Woolf'),
    (16, 'Charles Dickens'),
    (17, 'Leo Tolstoy'),
    (18, 'Emily Bronte'),
    (19, 'Isaac Asimov'),
    (20, 'Gabrielle Zevin'),
    (21, 'Khaled Hosseini'),
    (22, 'Kazuo Ishiguro'),
    (23, 'C.S. Lewis'),
    (24, 'Jhumpa Lahiri'),
    (25, 'George R.R. Martin'),
    (26, 'Roald Dahl'),
    (27, 'Neil Gaiman'),
    (28, 'H.P. Lovecraft'),
    (29, 'Ayn Rand'),
    (30, 'Ray Bradbury');
    